# Generated by Django 4.1.3 on 2022-12-18 05:59

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="tags.UnicodeTaggedItem",
                to="taggit.Tag",
                verbose_name="Tag subscriptions",
            ),
        ),
    ]
