# Generated by Django 4.1.3 on 2023-02-05 17:45

from django.db import migrations, models
import users.models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                default="user/default_avatar.jpg",
                upload_to=users.models.user_avatars_path,
                validators=[users.validators.validate_image],
                verbose_name="Profile picture",
            ),
        ),
    ]
