# Generated by Django 4.1.3 on 2022-12-30 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
        ("users", "0002_user_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.RemoveField(
            model_name="user",
            name="socials",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tags",
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="user/default_avatar.jpg",
                        upload_to=users.models.user_avatars_path,
                        verbose_name="Profile picture",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, max_length=700, verbose_name="Bio"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Location"
                    ),
                ),
                (
                    "socials",
                    models.JSONField(
                        blank=True,
                        default=users.models.default_social_media_json,
                        verbose_name="Social Media Links",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="tags.UnicodeTaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tag subscriptions",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profile",
                    ),
                ),
            ],
        ),
    ]
