# Generated by Django 4.1.3 on 2023-01-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_avatar_remove_user_bio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeEmailToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=255, unique=True, verbose_name="Token"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Your name appear around NoteD where you post or do actions.",
                max_length=50,
                verbose_name="Full Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Username should include only latin letters, digits and dots.             Username can't start and end with a dot or don't contain letters.             Digits can be added only at the end.",
                max_length=150,
                unique=True,
                verbose_name="Username",
            ),
        ),
    ]
