# Generated by Django 4.2 on 2023-04-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="image_url",
            field=models.URLField(max_length=1000, null=True, verbose_name="Image URL"),
        ),
        migrations.AddField(
            model_name="note",
            name="preview_text",
            field=models.CharField(
                default="", max_length=300, verbose_name="Preview text"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="weight",
            field=models.SmallIntegerField(default=0, verbose_name="Weight"),
        ),
    ]
