# Generated by Django 4.1.3 on 2022-12-17 15:57

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='Add tags. Separate tags by using "Enter" or comma.\n        You can add maximum 5 tags, and length of tags should be less than 25\n        symbols.',
                through="tags.UnicodeTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
