# Generated by Django 4.1.3 on 2022-12-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_note_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="Views"),
        ),
    ]
