# Generated by Django 4.1.3 on 2022-12-20 17:02

import content.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_note_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="body_raw",
            field=content.fields.MarkdownField(
                rendered_field="body_html", verbose_name="Markdown body"
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="link",
            field=models.URLField(
                blank=True, default="", max_length=255, verbose_name="External link"
            ),
        ),
    ]
