# Generated by Django 4.1.3 on 2022-12-20 19:06

import content.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_note_body_raw_alter_source_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="body_raw",
            field=content.fields.MarkdownField(
                blank=True, rendered_field="body_html", verbose_name="Markdown body"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="summary",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Write summary on the note in 250 symbols.",
                max_length=250,
                verbose_name="Summary",
            ),
        ),
    ]
