# Generated by Django 4.1.3 on 2022-12-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_alter_note_body_raw_alter_note_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="lang",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian")],
                default="ru",
                max_length=2,
                verbose_name="Language",
            ),
        ),
    ]
