# Generated by Django 4.1.3 on 2022-12-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_note_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="lang",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian"), ("er", "Undetected")],
                default="er",
                max_length=2,
                verbose_name="Language",
            ),
        ),
    ]
