# Generated by Django 4.1.3 on 2023-01-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="verb",
            field=models.CharField(
                choices=[
                    ("new_note", "A user posted a note."),
                    ("new_source", "A user posted a note with new source."),
                    ("new_user", "Has created an account."),
                    ("follow_tag", "A user stared following a tag."),
                    ("bookmark", "A user added a note to his bookmarks."),
                    ("like", "A user liked a note."),
                    ("download", "A user downloaded a note."),
                    ("follow_user", "A user stared following another user."),
                ],
                max_length=255,
            ),
        ),
    ]
